### ISSUE TITLE
OpenSSL compatibility

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/promisedyntracer#27]
Our code depends on openSSL version 1.1+ but some systems (eg. Ubuntu) provide 1.0.2, which means there's an additional step when building the project. OpenSSL 1.1 and 1.0.2 have different APIs, which is the only (?) problem. I think we could use the preprocessor to switch APIs. 

I experimented with this a bit (in a separate branch) following the advice from the OpenSSL wiki (https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes), but it needs debugging etc.

**Comment by aviralg** [comment]
3 months from now, new Ubuntu LTS will be released with the new version of OpenSSL. 
OpenSSL 1.0.2 was released in 2015 and is pretty old now. Since installation of OpenSSL 1.1 on current Ubuntu LTS is painless, should we care at all? I believe servers (due to security reasons) will use the newer version of OpenSSL. At least that is the case on the server you are running the experiments on.
Also, this additional step is one time and only necessary for new  people. I wonder how many new people will contribute code to this project in the next 3 months.
If we don't foresee anyone else contributing to the project, this enhancement, regardless of how simple it is, seems futile to me.

**Comment by kondziu** [comment]
Over the last three months I had to deal with it on my work laptop, ELE-2 machines, a local cluster in Prague, my other work laptop, my laptop again after I re-installed the OS, my home laptop when I wanted to work at home, and Artem's laptop. Within the next three months we are supposed to get new servers in Prague and new laptops. I also want to install it on my desktop at home. I also don't see myself switching to the new OS as soon as it's out. So I think it's worth it.

**Comment by kondziu** [comment]
I forgot about ginger and violet ;)
